from tkinter import *

t = Tk()
t.geometry('440x400')

form_frame= Frame(t,bd=2,relief="solid",padx=10,pady=10)
form_frame.grid(pady=20,padx=20)
l1 = Label(t,text="Enter Name\t\t").grid(row=0,column=0)
l1 = Label(t,text=" ").grid(row=1,column=0)
l2 = Label(t,text="Enter Email\t\t").grid(row=2,column=0)
l1 = Label(t,text=" ").grid(row=3,column=0)
l3 = Label(t,text="Contact Number\t\t").grid(row=4,column=0)
l1 = Label(t,text=" ").grid(row=5,column=0)
l4 = Label(t,text="Select Gender\t\t").grid(row=6,column=0)
l1 = Label(t,text=" ").grid(row=7,column=0)
l4 = Label(t,text="Select Country\t\t").grid(row=8,column=0)
l1 = Label(t,text=" ").grid(row=9,column=0)
l4 = Label(t,text="Enter Password\t\t").grid(row=10,column=0)
l1 = Label(t,text=" ").grid(row=11,column=0)
l4 = Label(t,text="Re-Enter Password\t").grid(row=12,column=0)
l1 = Label(t,text=" ").grid(row=13,column=0)
e1 = Entry(t,bd=5).grid(row=0,column=1)
e2 = Entry(t,bd=5).grid(row=2,column=1)
e3 = Entry(t,bd=5).grid(row=4,column=1)
r1 = Radiobutton(t,text="Male").grid(row=6,column=1)
r2 = Radiobutton(t,text="Female").grid(row=6,column=2)
r3 = Radiobutton(t,text="Others").grid(row=6,column=3)
e4 = Entry(t,bd=5).grid(row=8,column=1)
e5 = Entry(t,bd=5).grid(row=10,column=1)
e6 = Entry(t,bd=5).grid(row=12,column=1)
b1 = Button(t,text="Register",bd=3).grid(row=14,column=1)
t.mainloop()